[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/dist"

# Ensures React Router works â€” redirects all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: force HTTPS
[[redirects]]
  from = "http://aplusacademy.pk/*"
  to = "https://aplusacademy.pk/:splat"
  status = 301
  force = true
